{
 "title": "Services dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Demo server requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(get_pairs_total{instance=\"demo_server:8002\"}[60s])",
     "legendFormat": "Requests received"
    }
   ]
  },
  {
   "title": "Data requester",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(request_total{instance=\"data_requester:7003\"}[60s])",
     "legendFormat": "Requests sent"
    },
    {
     "expr": "increase(success_response_total{instance=\"data_requester:7003\"}[60s])",
     "legendFormat": "Success responses"
    },
    {
     "expr": "increase(error_response_total{instance=\"data_requester:7003\"}[60s])",
     "legendFormat": "Error responses"
    }
   ]
  },
  {
   "title": "Data processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(src_data_received_total{instance=\"data_processor:7004\"}[60s])",
     "legendFormat": "Received from src_data topic"
    },
    {
     "expr": "increase(processed_pairs_total{instance=\"data_processor:7004\"}[60s])",
     "legendFormat": "Processed currency pairs"
    },
    {
     "expr": "increase(processed_data_sent_total{instance=\"data_processor:7004\"}[60s])",
     "legendFormat": "Sent to processed_data topic"
    }
   ]
  },
  {
   "title": "Data aggregator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(processed_data_received_total{instance=\"data_aggregator:7005\"}[60s])",
     "legendFormat": "Received from processed_data topic"
    },
    {
     "expr": "increase(pairs_average_aggregated_total{instance=\"data_aggregator:7005\"}[60s])",
     "legendFormat": "Average calculated"
    }
   ]
  },
  {
   "title": "DB loader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(average_topic_received_total{instance=\"db_loader:7006\"}[60s])",
     "legendFormat": "Received from average_topic "
    },
    {
     "expr": "increase(processed_data_received_total{instance=\"db_loader:7006\"}[60s])",
     "legendFormat": "Received from processed_data topic"
    },
    {
     "expr": "increase(average_topic_saved_total{instance=\"db_loader:7006\"}[60s])",
     "legendFormat": "Saved average values"
    },
    {
     "expr": "increase(processed_data_saved_total{instance=\"db_loader:7006\"}[60s])",
     "legendFormat": "Saved pairs values"
    }
   ]
  },
  {
   "title": "API gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(get_currencies_total{instance=\"api_gateway:8007\"}[60s])",
     "legendFormat": "Currencies request"
    },
    {
     "expr": "increase(get_average_total{instance=\"api_gateway:8007\"}[60s])",
     "legendFormat": "Average requests"
    }
   ]
  }
 ]
}